# Generated by Django 4.2.14 on 2024-07-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0003_book_author_book_is_bestselling_alter_book_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
